import { PermissionMatrix } from '@real-estate-erp/types';

export const PERMISSION_MATRIX: PermissionMatrix = {
  super_admin: ['*:*'],
  director: [
    'company:*',
    'branch:*',
    'employee:*',
    'attendance:*',
    'campaign:*',
    'lead:*',
    'followup:*',
    'project:*',
    'layout:*',
    'plot:*',
    'booking:*',
    'customer:*',
    'payments:*',
    'vehicle:*',
    'expenses:*',
    'reports:*',
    'dashboard:*',
    'settings:*',
    'notifications:*',
    'ai:*',
  ],
  branch_manager: [
    'branch:read',
    'branch:update',
    'employee:read',
    'employee:update',
    'attendance:*',
    'campaign:read',
    'lead:*',
    'followup:*',
    'project:read',
    'layout:read',
    'plot:read',
    'plot:update',
    'booking:*',
    'customer:*',
    'payments:read',
    'payments:approve',
    'vehicle:read',
    'expenses:*',
    'reports:*',
    'dashboard:*',
    'notifications:*',
  ],
  marketing_manager: [
    'campaign:*',
    'lead:*',
    'followup:*',
    'reports:read',
    'reports:export',
    'dashboard:read',
    'notifications:*',
    'ai:*',
  ],
  marketing_executive: [
    'campaign:read',
    'campaign:update',
    'lead:create',
    'lead:read',
    'lead:update',
    'lead:import',
    'followup:create',
    'followup:read',
    'followup:update',
    'dashboard:read',
    'notifications:read',
  ],
  sales_manager: [
    'lead:*',
    'followup:*',
    'project:read',
    'layout:read',
    'plot:read',
    'plot:update',
    'booking:*',
    'customer:*',
    'reports:read',
    'dashboard:read',
    'notifications:*',
  ],
  sales_executive: [
    'lead:read',
    'lead:update',
    'followup:create',
    'followup:read',
    'followup:update',
    'project:read',
    'layout:read',
    'plot:read',
    'booking:create',
    'booking:read',
    'booking:update',
    'customer:create',
    'customer:read',
    'customer:update',
    'dashboard:read',
    'notifications:read',
  ],
  telecaller: [
    'lead:create',
    'lead:read',
    'lead:update',
    'followup:create',
    'followup:read',
    'followup:update',
    'customer:read',
    'dashboard:read',
    'notifications:read',
  ],
  accountant: [
    'payments:*',
    'expenses:*',
    'reports:*',
    'booking:read',
    'booking:update',
    'customer:read',
    'dashboard:read',
    'notifications:*',
  ],
  driver: [
    'vehicle:read',
    'vehicle:update',
    'attendance:create',
    'attendance:read',
    'dashboard:read',
    'notifications:read',
  ],
  customer: [
    'dashboard:read',
    'booking:read',
    'payments:read',
    'customer:read',
    'customer:update',
    'notifications:read',
  ],
};
