import { RoleDefinition, UserRole } from '@real-estate-erp/types';

export const ROLE_DEFINITIONS: Record<UserRole, RoleDefinition> = {
  super_admin: {
    id: 'super_admin',
    name: 'Super Admin',
    level: 100,
    description: 'Full root access to all system resources, settings, and organizations.',
    manageableRoles: [
      'director',
      'branch_manager',
      'marketing_manager',
      'marketing_executive',
      'sales_manager',
      'sales_executive',
      'telecaller',
      'accountant',
      'driver',
      'customer',
    ],
  },
  director: {
    id: 'director',
    name: 'Director',
    level: 90,
    description: 'Executive management across company operations, branches, and financials.',
    manageableRoles: [
      'branch_manager',
      'marketing_manager',
      'marketing_executive',
      'sales_manager',
      'sales_executive',
      'telecaller',
      'accountant',
      'driver',
      'customer',
    ],
  },
  branch_manager: {
    id: 'branch_manager',
    name: 'Branch Manager',
    level: 80,
    description: 'Branch head governing branch employees, sales, leads, and expenses.',
    manageableRoles: [
      'marketing_manager',
      'marketing_executive',
      'sales_manager',
      'sales_executive',
      'telecaller',
      'accountant',
      'driver',
      'customer',
    ],
  },
  marketing_manager: {
    id: 'marketing_manager',
    name: 'Marketing Manager',
    level: 70,
    description: 'Oversees marketing campaigns, lead acquisition, and marketing team.',
    manageableRoles: ['marketing_executive', 'telecaller'],
  },
  marketing_executive: {
    id: 'marketing_executive',
    name: 'Marketing Executive',
    level: 60,
    description: 'Executes campaigns, captures leads, and tracks initial interactions.',
    manageableRoles: [],
  },
  sales_manager: {
    id: 'sales_manager',
    name: 'Sales Manager',
    level: 70,
    description: 'Manages sales operations, agent assignments, plots, and booking approvals.',
    manageableRoles: ['sales_executive', 'telecaller'],
  },
  sales_executive: {
    id: 'sales_executive',
    name: 'Sales Executive',
    level: 60,
    description: 'Handles site visits, client followups, property bookings, and closing deals.',
    manageableRoles: [],
  },
  telecaller: {
    id: 'telecaller',
    name: 'Telecaller',
    level: 50,
    description: 'Outbound tele-calling, lead qualification, and appointment scheduling.',
    manageableRoles: [],
  },
  accountant: {
    id: 'accountant',
    name: 'Accountant',
    level: 75,
    description: 'Manages payments, invoices, financial vouchers, and expense approvals.',
    manageableRoles: [],
  },
  driver: {
    id: 'driver',
    name: 'Driver',
    level: 40,
    description: 'Fleet & site-visit vehicle operation, logbooks, and maintenance updates.',
    manageableRoles: [],
  },
  customer: {
    id: 'customer',
    name: 'Customer',
    level: 10,
    description: 'External client accessing personal property bookings, receipts, and updates.',
    manageableRoles: [],
  },
};
