import { LeadCaptureRequestDTO } from './dto';
import { LeadValidator } from './validators';
import { LeadMatchingService } from './LeadMatchingService';
import { CampaignAttributionService } from './CampaignAttributionService';
import { RoutingService } from './RoutingService';
import { LeadFactory } from './LeadFactory';
import { LeadRepository } from '../../repositories/LeadRepository';
import { LeadModel } from '../../models/leads';
import { InteractionService } from '../InteractionService';

// Fallback to simpler Workflow executor or just skip importing if we don't have it directly.
// As per requirement, every Lead starts a Workflow.
import { WorkflowExecutor } from '../workflow/WorkflowExecutor';

export class LeadAcquisitionService {
  private leadMatchingService: LeadMatchingService;
  private campaignAttributionService: CampaignAttributionService;
  private routingService: RoutingService;
  private leadRepository: LeadRepository;
  private interactionService: InteractionService;
  private workflowExecutor: WorkflowExecutor;

  constructor() {
    this.leadMatchingService = new LeadMatchingService();
    this.campaignAttributionService = new CampaignAttributionService();
    this.routingService = new RoutingService();
    this.leadRepository = new LeadRepository();
    this.interactionService = new InteractionService();
    this.workflowExecutor = new WorkflowExecutor();
  }

  public async acquireLead(dto: LeadCaptureRequestDTO, userId: string = 'SYSTEM'): Promise<LeadModel> {
    // 1. Validation
    LeadValidator.validateCaptureRequest(dto);

    // 2. Duplicate Detection & Person Matching
    const matchResult = await this.leadMatchingService.matchOrCreatePerson(dto, userId);

    // 3. Routing (Round robin, owner, etc.)
    const routingDetails = await this.routingService.routeLead(dto);

    // 4. Campaign Attribution & Scoring (Multi-touch support)
    // We assume the lead ID is generated by the repository later, but for attribution,
    // we can generate a temporary ID or just use personId. Let's create a temporary UUID.
    const tempLeadId = `lead_${Date.now()}`;
    const newTouchpoint = this.campaignAttributionService.createTouchpoint(dto, tempLeadId);
    
    // Check if person already has an active lead to get existing attribution
    // In a real implementation, you would fetch `existingAttribution` from DB
    const existingAttribution = null; 
    
    this.campaignAttributionService.computeAttribution(tempLeadId, existingAttribution, newTouchpoint);

    // 5. Construct Lead Model via Factory
    const leadInput = LeadFactory.createNewLead(dto, matchResult.personId, newTouchpoint, routingDetails);

    // 6. Create Lead
    const lead = await this.leadRepository.create(leadInput, userId);

    // 7. Create First Interaction (Timeline Event)
    await this.interactionService.recordInteraction({
      personId: matchResult.personId,
      type: 'NOTE', // Standard fallback, can be derived from source
      projectId: dto.projectId,
      date: new Date().toISOString(),
      status: 'COMPLETED',
      priority: 'MEDIUM',
      notes: `Lead acquired from ${dto.sourceCode} via ${routingDetails.routingStrategy}`,
    }, userId);

    // 8. Start Workflow
    try {
      await this.workflowExecutor.startWorkflow(
        'DEFAULT_LEAD_WORKFLOW', // definitionId
        lead.id,                 // entityId
        'Lead',                  // entityType
        userId,                  // userId
        {}                       // context
      );
    } catch (error) {
      console.warn('Failed to start workflow during lead acquisition:', error);
    }

    return lead;
  }
}
