import React, { useState } from 'react';
import {
  Box,
  Typography,
  Grid,
  Card,
  CardContent,
  Select,
  MenuItem,
  FormControl,
  Paper,
  List,
  ListItemButton,
  ListItemIcon,
  ListItemText,
  Chip,
  Divider,
  Button,
  Table,
  TableHead,
  TableBody,
  TableRow,
  TableCell,
  TableContainer,
  useTheme,
} from '@mui/material';
import AssessmentIcon from '@mui/icons-material/Assessment';
import DownloadIcon from '@mui/icons-material/Download';
import PrintIcon from '@mui/icons-material/Print';

interface ReportDefinition {
  id: number;
  title: string;
  category: string;
  data: { label: string; count: number; share: string }[];
  summary: string;
}

const REPORTS_CATALOG: ReportDefinition[] = [
  {
    id: 1,
    title: 'Leads by Source',
    category: 'Acquisition',
    summary: 'Distribution of inbound prospects by marketing channel over the selected period.',
    data: [
      { label: 'Facebook & Instagram Ads', count: 1890, share: '45.0%' },
      { label: 'Physical Walk-ins / Site Visitors', count: 1050, share: '25.0%' },
      { label: 'Channel Partner & Member Referrals', count: 630, share: '15.0%' },
      { label: 'Google Search & SEO Blog', count: 420, share: '10.0%' },
      { label: 'Direct Print & Newspaper Ads', count: 210, share: '5.0%' },
    ],
  },
  {
    id: 2,
    title: 'Leads by Campaign',
    category: 'Campaigns',
    summary: 'Breakdown of inquiry volume generated by individual active campaigns.',
    data: [
      { label: 'Summer Festive Offer 2026', count: 1240, share: '29.5%' },
      { label: 'Broker Referral Incentive Drive', count: 1013, share: '24.1%' },
      { label: 'Website Organic Inquiries', count: 890, share: '21.2%' },
      { label: 'NRI Direct Investment Drive', count: 640, share: '15.2%' },
      { label: 'Metro Outdoor Hoardings', count: 420, share: '10.0%' },
    ],
  },
  {
    id: 3,
    title: 'Leads by Project',
    category: 'Projects',
    summary: 'Client interest and plot inquiries categorized across venture developments.',
    data: [
      { label: 'Sunrise Enclave (Mokila)', count: 2140, share: '50.9%' },
      { label: 'Green Meadows (Shadnagar)', count: 1250, share: '29.7%' },
      { label: 'Royal Palms (Adibatla)', count: 813, share: '19.4%' },
    ],
  },
  {
    id: 4,
    title: 'Telecaller Performance & Connect Rate',
    category: 'Telecalling',
    summary: 'Outbound tele-calling call completions, reach rate, and visit bookings.',
    data: [
      { label: 'Sunita Reddy (Senior Telecaller Lead)', count: 1204, share: '32.1%' },
      { label: 'Kiran Rao (Inbound Telecaller)', count: 950, share: '25.3%' },
      { label: 'Meena Kumari (Outbound Telesales)', count: 840, share: '22.4%' },
      { label: 'Sneha Latha (Relationship Executive)', count: 760, share: '20.2%' },
    ],
  },
  {
    id: 5,
    title: 'Cost Per Lead (CPL) by Channel',
    category: 'Finance',
    summary: 'Direct marketing expenditure divided by valid prospects acquired.',
    data: [
      { label: 'Google Search Ads', count: 48, share: '₹48.50 / lead' },
      { label: 'Meta (Facebook / Instagram)', count: 36, share: '₹36.29 / lead' },
      { label: 'SMS & WhatsApp Bulk Blast', count: 12, share: '₹12.00 / lead' },
      { label: 'Outdoor Billboards', count: 185, share: '₹185.00 / lead' },
    ],
  },
  {
    id: 6,
    title: 'Site Visits by Source',
    category: 'Conversion',
    summary: 'In-person plot tours completed by origin source.',
    data: [
      { label: 'Facebook & Instagram Ads', count: 410, share: '46.0%' },
      { label: 'Channel Partner & Agent Referrals', count: 245, share: '27.5%' },
      { label: 'Direct Walk-in & Highway Billboard', count: 140, share: '15.7%' },
      { label: 'Organic Website & SEO Inquiries', count: 97, share: '10.8%' },
    ],
  },
  {
    id: 7,
    title: 'Campaign Conversion Funnel',
    category: 'Conversion',
    summary: 'End-to-end throughput from initial click to registered plot deed.',
    data: [
      { label: '1. Ad Impressions & Clicks', count: 45200, share: '100%' },
      { label: '2. Inbound Leads Captured', count: 4203, share: '9.3%' },
      { label: '3. Contacted & Pre-Qualified', count: 2890, share: '6.4%' },
      { label: '4. Physical Site Visits Attended', count: 892, share: '2.0%' },
      { label: '5. Bookings & Token Paid', count: 184, share: '0.41%' },
    ],
  },
  {
    id: 8,
    title: 'Agent MLM Commission Payouts by Rank',
    category: 'MLM Network',
    summary: 'Commission volume earned and disbursed categorized across multi-tier hierarchy levels.',
    data: [
      { label: 'Sr CGM (Senior Chief General Manager)', count: 645000, share: '35.0% (₹6.45L)' },
      { label: 'CGM (Chief General Manager)', count: 480000, share: '26.0% (₹4.80L)' },
      { label: 'ZGM (Zonal General Manager)', count: 320000, share: '17.3% (₹3.20L)' },
      { label: 'DGM (Deputy General Manager)', count: 210000, share: '11.4% (₹2.10L)' },
      { label: 'AGM (Assistant General Manager)', count: 125000, share: '6.8% (₹1.25L)' },
      { label: 'Field Associate (Direct Channel)', count: 65000, share: '3.5% (₹0.65L)' },
    ],
  },
  {
    id: 9,
    title: 'Site-Visit Fleet Mileage & Fuel Efficiency',
    category: 'Fleet Operations',
    summary: 'Vehicle dispatch count, total distance traversed, and fuel economy benchmarks.',
    data: [
      { label: 'Toyota Innova Crysta (TS 09 UB 1001)', count: 148, share: '14.2 km/L (Diesel)' },
      { label: 'Force Tempo Traveller (TS 08 EX 4050)', count: 215, share: '10.8 km/L (Diesel)' },
      { label: 'Mahindra Scorpio-N (TS 09 Z 8899)', count: 174, share: '13.5 km/L (Diesel)' },
      { label: 'Maruti Suzuki Ertiga (TS 07 HK 2020)', count: 92, share: '22.4 km/kg (CNG)' },
      { label: 'Toyota Innova Hycross (TS 08 FA 3311)', count: 68, share: '18.6 km/L (Hybrid)' },
      { label: 'Tata Winger Luxury (TS 09 WL 7788)', count: 126, share: '11.2 km/L (Diesel)' },
    ],
  },
  {
    id: 10,
    title: 'Geo-Fenced Staff Attendance & Punctuality',
    category: 'Human Resources',
    summary: 'Biometric and GPS geofenced punch-in verification rates across departments.',
    data: [
      { label: 'Field Sales Executives (Venture Sites)', count: 94, share: '94.2% Geo-Verified' },
      { label: 'Fleet Drivers & Pilots (Site Trips)', count: 98, share: '98.5% Geo-Verified' },
      { label: 'Telecalling & CRM Desk (Head Office)', count: 96, share: '96.0% Verified' },
      { label: 'Branch Managers & Directors', count: 99, share: '99.1% Verified' },
      { label: 'Finance & Accounting Wing', count: 97, share: '97.4% Verified' },
    ],
  },
];

export const MarketingReports: React.FC = () => {
  const theme = useTheme();
  const [selectedReportId, setSelectedReportId] = useState<number>(1);
  const [timeRange, setTimeRange] = useState('30D');

  const activeReport = REPORTS_CATALOG.find((r) => r.id === selectedReportId) || REPORTS_CATALOG[0];

  return (
    <Box sx={{ p: { xs: 2, md: 3 } }}>
      {/* Header */}
      <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 3, flexWrap: 'wrap', gap: 2 }}>
        <Box>
          <Typography variant="h4" fontWeight={700} color="text.primary">
            Marketing & Analytics Reports
          </Typography>
          <Typography variant="body2" color="text.secondary">
            Enterprise marketing intelligence, acquisition channels, conversion funnels, and ROI metrics
          </Typography>
        </Box>

        <Box sx={{ display: 'flex', gap: 1.5, alignItems: 'center' }}>
          <FormControl size="small" sx={{ minWidth: 140 }}>
            <Select value={timeRange} onChange={(e) => setTimeRange(e.target.value)}>
              <MenuItem value="7D">Last 7 Days</MenuItem>
              <MenuItem value="30D">Last 30 Days</MenuItem>
              <MenuItem value="QUARTER">This Quarter</MenuItem>
              <MenuItem value="YEAR">This Year</MenuItem>
            </Select>
          </FormControl>
          <Button variant="outlined" startIcon={<DownloadIcon />} size="small">
            Export CSV
          </Button>
          <Button variant="outlined" startIcon={<PrintIcon />} size="small">
            Print
          </Button>
        </Box>
      </Box>

      {/* Top 3 KPI Highlights */}
      <Grid container spacing={2.5} sx={{ mb: 3.5 }}>
        <Grid item xs={12} md={4}>
          <Card elevation={2} sx={{ borderRadius: 2.5, borderTop: `5px solid ${theme.palette.primary.main}` }}>
            <CardContent sx={{ p: 2.5 }}>
              <Typography variant="subtitle2" color="text.secondary">Primary Inbound Channel</Typography>
              <Typography variant="h5" fontWeight={700} color="primary" sx={{ my: 0.5 }}>
                Facebook Ads (45%)
              </Typography>
              <Typography variant="caption" color="text.secondary">
                1,890 leads captured in selected timeframe
              </Typography>
            </CardContent>
          </Card>
        </Grid>
        <Grid item xs={12} md={4}>
          <Card elevation={2} sx={{ borderRadius: 2.5, borderTop: `5px solid ${theme.palette.success.main}` }}>
            <CardContent sx={{ p: 2.5 }}>
              <Typography variant="subtitle2" color="text.secondary">Average Cost Per Lead (CPL)</Typography>
              <Typography variant="h5" fontWeight={700} color="success.main" sx={{ my: 0.5 }}>
                ₹ 45.20
              </Typography>
              <Typography variant="caption" color="success.main">
                ↓ 12% lower cost than industry benchmark
              </Typography>
            </CardContent>
          </Card>
        </Grid>
        <Grid item xs={12} md={4}>
          <Card elevation={2} sx={{ borderRadius: 2.5, borderTop: `5px solid ${theme.palette.secondary.main}` }}>
            <CardContent sx={{ p: 2.5 }}>
              <Typography variant="subtitle2" color="text.secondary">Total Inquiries Processed</Typography>
              <Typography variant="h5" fontWeight={700} color="secondary.main" sx={{ my: 0.5 }}>
                4,203 Leads
              </Typography>
              <Typography variant="caption" color="text.secondary">
                892 site visits delivered (21.2% conversion)
              </Typography>
            </CardContent>
          </Card>
        </Grid>
      </Grid>

      {/* Main Content: Report Selector + Active Report Details */}
      <Grid container spacing={3}>
        {/* Left Side: Report Catalog */}
        <Grid item xs={12} md={4}>
          <Paper elevation={1} sx={{ borderRadius: 2.5, overflow: 'hidden' }}>
            <Box sx={{ p: 2, bgcolor: theme.palette.action.hover, borderBottom: 1, borderColor: 'divider' }}>
              <Typography variant="subtitle1" fontWeight={700}>
                Available Management Reports
              </Typography>
              <Typography variant="caption" color="text.secondary">
                Select a report below to view full details
              </Typography>
            </Box>
            <List disablePadding>
              {REPORTS_CATALOG.map((report) => (
                <ListItemButton
                  key={report.id}
                  selected={selectedReportId === report.id}
                  onClick={() => setSelectedReportId(report.id)}
                  sx={{
                    py: 1.5,
                    borderBottom: `1px solid ${theme.palette.divider}`,
                    '&.Mui-selected': {
                      bgcolor: theme.palette.action.selected,
                      borderLeft: `4px solid ${theme.palette.primary.main}`,
                    },
                  }}
                >
                  <ListItemIcon sx={{ minWidth: 36, color: selectedReportId === report.id ? 'primary.main' : 'inherit' }}>
                    <AssessmentIcon fontSize="small" />
                  </ListItemIcon>
                  <ListItemText
                    primary={report.title}
                    primaryTypographyProps={{ variant: 'body2', fontWeight: selectedReportId === report.id ? 700 : 500 }}
                  />
                  <Chip label={report.category} size="small" variant="outlined" sx={{ fontSize: '0.65rem', height: 20 }} />
                </ListItemButton>
              ))}
            </List>
          </Paper>
        </Grid>

        {/* Right Side: Active Report Display */}
        <Grid item xs={12} md={8}>
          <Paper elevation={1} sx={{ borderRadius: 2.5, p: 3 }}>
            <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 1 }}>
              <Typography variant="h5" fontWeight={700} color="primary">
                {activeReport.title}
              </Typography>
              <Chip label={activeReport.category} color="primary" size="small" sx={{ fontWeight: 600 }} />
            </Box>
            <Typography variant="body2" color="text.secondary" sx={{ mb: 3 }}>
              {activeReport.summary}
            </Typography>

            <Divider sx={{ mb: 3 }} />

            <TableContainer component={Paper} variant="outlined" sx={{ borderRadius: 2 }}>
              <Table>
                <TableHead sx={{ bgcolor: theme.palette.action.hover }}>
                  <TableRow>
                    <TableCell sx={{ fontWeight: 700 }}>Dimension / Segment</TableCell>
                    <TableCell align="right" sx={{ fontWeight: 700 }}>Volume / Metric</TableCell>
                    <TableCell align="right" sx={{ fontWeight: 700 }}>Percentage / Share</TableCell>
                  </TableRow>
                </TableHead>
                <TableBody>
                  {activeReport.data.map((row, idx) => (
                    <TableRow key={idx} hover>
                      <TableCell sx={{ fontWeight: 600 }}>{row.label}</TableCell>
                      <TableCell align="right">{row.count.toLocaleString()}</TableCell>
                      <TableCell align="right">
                        <Chip label={row.share} size="small" color="primary" variant="outlined" sx={{ fontWeight: 600 }} />
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </TableContainer>
          </Paper>
        </Grid>
      </Grid>
    </Box>
  );
};

export default MarketingReports;
