export const FIRESTORE_COLLECTIONS = {
  COMPANIES: 'companies',
  BRANCHES: 'branches',
  ROLES: 'roles',
  PERMISSIONS: 'permissions',
  USERS: 'users',
  EMPLOYEES: 'employees',
  DEPARTMENTS: 'departments',
  DESIGNATIONS: 'designations',
  TEAMS: 'teams',
  BUSINESS_UNITS: 'business_units',
  ORGANIZATION_SETTINGS: 'organization_settings',
  PROJECTS: 'projects',
  LAYOUTS: 'layouts',
  BLOCKS: 'blocks',
  PLOTS: 'plots',
  LEADS: 'leads',
  LEAD_SOURCES: 'lead_sources',
  LEAD_ACTIVITIES: 'lead_activities',
  FOLLOW_UPS: 'follow_ups',
  CAMPAIGNS: 'campaigns',
  CAMPAIGN_EXPENSES: 'campaign_expenses',
  CUSTOMERS: 'customers',
  BOOKINGS: 'bookings',
  PAYMENTS: 'payments',
  RECEIPTS: 'receipts',
  VEHICLES: 'vehicles',
  DRIVERS: 'drivers',
  VEHICLE_TRIPS: 'vehicle_trips',
  FUEL_ENTRIES: 'fuel_entries',
  EXPENSES: 'expenses',
  ATTENDANCE: 'attendance',
  NOTIFICATIONS: 'notifications',
  DOCUMENTS: 'documents',
  MEDIA: 'media',
  SETTINGS: 'settings',
  AUDIT_LOGS: 'audit_logs',
  AI_SUGGESTIONS: 'ai_suggestions',
  PERSONS: 'persons',
} as const;

export type CollectionName = (typeof FIRESTORE_COLLECTIONS)[keyof typeof FIRESTORE_COLLECTIONS];
