export interface CommandCenterKPIs {
  totalLeads: number;
  qualifiedLeads: number;
  siteVisits: number;
  bookings: number;
  fullPayments: number;
  registrations: number;
  
  grossSales: number;
  collectedAmount: number;
  outstandingAmount: number;
  commissionPayable: number;
  
  availableInventory: number;
  bookedInventory: number;
  registeredInventory: number;
  
  afterSalesOpenCases: number;
}

export type AISeverity = 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
export type AIConfidence = 'LOW' | 'MEDIUM' | 'HIGH';

export interface AIInsight {
  /** The metric or indicator observed */
  metric: string;
  
  /** The observation text */
  observation: string;
  
  /** Factual data supporting the observation */
  evidence: string;
  
  /** Severity level of the insight */
  severity: AISeverity;
  
  /** The likely cause generated by analytics */
  possibleCause: string;
  
  /** Recommended action for management */
  recommendedAction: string;
  
  /** Confidence score in this insight */
  confidence: AIConfidence;
}

export interface DashboardFilter {
  startDate?: Date | string;
  endDate?: Date | string;
  companyId?: string;
  branchId?: string;
  projectId?: string;
  layoutId?: string;
  campaignId?: string;
  sourceId?: string;
  marketingTeamId?: string;
  networkMemberId?: string;
  executiveId?: string;
}

export interface ExecutiveDashboardData {
  kpis: CommandCenterKPIs;
  insights: AIInsight[];
}
