export enum CommissionEventType {
  COMMISSION_RULE_CREATED = 'COMMISSION_RULE_CREATED',
  COMMISSION_RULE_UPDATED = 'COMMISSION_RULE_UPDATED',
  COMMISSION_CALCULATED = 'COMMISSION_CALCULATED',
  COMMISSION_APPROVED = 'COMMISSION_APPROVED',
  COMMISSION_PAYABLE = 'COMMISSION_PAYABLE',
  COMMISSION_PAID = 'COMMISSION_PAID',
  COMMISSION_REVERSED = 'COMMISSION_REVERSED',
}
