export const NetworkEvents = {
  NETWORK_MEMBER_CREATED: 'NETWORK_MEMBER_CREATED',
  NETWORK_MEMBER_UPDATED: 'NETWORK_MEMBER_UPDATED',
  NETWORK_MEMBER_PARENT_CHANGED: 'NETWORK_MEMBER_PARENT_CHANGED',
  NETWORK_POSITION_CHANGED: 'NETWORK_POSITION_CHANGED',
} as const;

export const CommissionEvents = {
  COMMISSION_RULE_CREATED: 'COMMISSION_RULE_CREATED',
  COMMISSION_RULE_UPDATED: 'COMMISSION_RULE_UPDATED',
  COMMISSION_CALCULATED: 'COMMISSION_CALCULATED',
  COMMISSION_APPROVED: 'COMMISSION_APPROVED',
  COMMISSION_PAYABLE: 'COMMISSION_PAYABLE',
  COMMISSION_PAID: 'COMMISSION_PAID',
  COMMISSION_REVERSED: 'COMMISSION_REVERSED',
} as const;

export const BookingPaymentEvents = {
  BOOKING_FULLY_PAID: 'BOOKING_FULLY_PAID',
} as const;
