export enum NetworkEventType {
  NETWORK_MEMBER_CREATED = 'NETWORK_MEMBER_CREATED',
  NETWORK_MEMBER_UPDATED = 'NETWORK_MEMBER_UPDATED',
  NETWORK_MEMBER_PARENT_CHANGED = 'NETWORK_MEMBER_PARENT_CHANGED',
  NETWORK_POSITION_CHANGED = 'NETWORK_POSITION_CHANGED',
}
